apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.opsta.net/student76/ratings
maintainers:
  - name: student76
    email: devop76@mail.kmutt.ac.th
sources:
  - https://github.com/pusit20574/bookinfo-ratings